version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node1
      ipfs: 'ipfs:5001'
#      ethereum: 'mainnet:https://bsc-dataseed.binance.org/'
#      ethereum: 'mainnet:https://apis.ankr.com/71587f62d0eb40e888077f21b64ed8dc/265e0768e28172e8a9431bd1112ab835/binance/full/test/'
      ethereum: 'mainnet:https://app-25b3eff4-1fcf-4da6-a31e-217e9273dbf6.hk.ankr.com/'
      GRAPH_LOG: info
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node1
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
